// plugin-template.ts — reference template for custom signature plugins
//
// Plugins generated by the scan skill's gap analysis follow this template's structure.
// When generating an actual plugin, the payload, detection patterns, and groups
// are customized based on the vulnerability class being detected.
//
// Output location: <cwd>/.gevanni/plugins/autoload/custom-<vuln-type>.ts
//
// .ts/.js files in the autoload directory are auto-discovered by discoverPluginFiles(),
// so no manual config.json entry is needed.
//
// Import paths are relative to gevanni's src/.
// Custom plugins are placed in .gevanni/plugins/autoload/ and loaded via
// gevanni's built-in plugin-loader dynamic import, so these relative imports resolve.

import { SignatureGroupId } from "../../types/branded.ts";
import type { Exchange } from "../../types/models.ts";
import { BuiltinMutationType, BuiltinPayload } from "../../types/models.ts";
import type { RunAuditContext } from "../../commands/run-audit.ts";
import { MutationFilteredSignaturePlugin } from "../signature/mutation-filtered.ts";

// ── Detection patterns ──────────────────────────────────────────────
// Define appropriate regex patterns or response analysis logic for each
// vulnerability class. Examples: SQL error messages, command execution output,
// XSS payload reflection, etc.

const DETECTION_PATTERNS: RegExp[] = [
  // Add response patterns that indicate a vulnerability
  /example error pattern/i,
];

export default class CustomPlugin extends MutationFilteredSignaturePlugin {
  // ── Plugin identifier ────────────────────────────────────────────
  // Naming convention: signature:custom-<kebab-case-vuln-type>
  // Examples: signature:custom-sqli-error, signature:custom-xss-reflected
  readonly name = "signature:custom-example";

  // ── Signature groups ──────────────────────────────────────────────
  // SignatureGroupId is a type-safe group identifier.
  // Available values depend on gevanni's group definitions.
  // Common ones: sqli, xss, cmdi, path-traversal, ssti, xxe, ldap,
  //              nosqli, crlf, xpath, ssi, prototype-pollution
  protected readonly groups = [SignatureGroupId("custom")];

  // ── Mutation types ──────────────────────────────────────────────
  // BuiltinMutationType:
  //   AppendValue  - append payload to existing value (most common)
  //   ReplaceValue - replace value entirely with payload
  //   InsertValue  - insert payload at the beginning of the value
  protected readonly mutationTypes = [BuiltinMutationType.AppendValue] as const;

  // ── Run audit ────────────────────────────────────────────────────
  // Receives the parameter (the target parameter being tested) and
  // replay (a request replay function) from the context,
  // sends the payload, and analyzes the response.
  //
  // Returns: Finding { vulnerable: boolean, evidence, request, response }
  protected async runAudit({ parameter, replay }: RunAuditContext) {
    // 1. Create payload
    const payload = BuiltinPayload.String("<payload>");

    // 2. Create mutation & replay request
    const result = await replay([
      parameter.createMutation(payload, BuiltinMutationType.AppendValue),
    ]);

    // 3. Collect all exchanges (including redirect chains)
    const allExchanges: Exchange[] = result.allExchanges;

    // 4. Analyze responses — detect patterns indicating vulnerability
    const matches = allExchanges.filter((ex) =>
      DETECTION_PATTERNS.some((p) =>
        p.test(ex.response.body?.toString() ?? "")
      )
    );

    // 5. Return finding
    return {
      vulnerable: matches.length > 0,
      evidence: {
        judgmentId: "custom-detection",
        exchanges: allExchanges,
        evidenceExchanges: matches,
      },
      request: result.exchange.request,
      response: result.exchange.response,
    };
  }
}

// ── Implementation patterns ──────────────────────────────────────────
//
// 【Pattern A】Error-message-based detection
//   When a vulnerability produces distinctive error messages in the response.
//   Examples: SQL errors, stack traces, LDAP errors
//   → Define DETECTION_PATTERNS and regex-match the response body
//
// 【Pattern B】Payload reflection detection
//   When the sent payload appears verbatim in the response.
//   Examples: Reflected XSS, SSTI expression evaluation results
//   → Check if the payload string is contained in the response
//   → const reflected = allExchanges.filter(ex => ex.response.body?.includes(payload))
//
// 【Pattern C】Diff-based detection
//   Detect by comparing response differences between safe and unsafe input.
//   Examples: Boolean-based SQLi, NoSQL boolean
//   → Compare replay results from safePayload and unsafePayload
//   → this.compareDiff(safeResult.exchange, unsafeResult.exchange, scenario.diffStrategy)
//
// 【Pattern D】Header analysis
//   When vulnerability traces appear in response headers.
//   Examples: CRLF injection, HTTP header injection
//   → Analyze ex.response.headers
//
// 【Pattern E】Status code analysis
//   When specific status codes indicate a vulnerability.
//   Examples: 500 error details, 403 bypass
//   → Check ex.response.status

// ── Constructor options (optional) ──────────────────────────────────
//
// When a plugin accepts configurable options:
//
// export default class CustomPlugin extends MutationFilteredSignaturePlugin {
//   readonly name = "signature:custom-example";
//   protected readonly groups = [SignatureGroupId("custom")];
//   protected readonly mutationTypes = [BuiltinMutationType.AppendValue] as const;
//   private opts: { threshold?: number; extraPatterns?: string[] };
//
//   constructor(options?: { threshold?: number; extraPatterns?: string[] }) {
//     super();
//     this.opts = options ?? {};
//   }
//
//   protected async runAudit(context: RunAuditContext) {
//     const threshold = this.opts.threshold ?? 0.5;
//     // ...
//   }
// }
//
// When using constructor options, list the plugin explicitly in config.json
// using the { file, options } format (autoload auto-discovery cannot pass options):
// {
//   "file": "./.gevanni/plugins/autoload/custom-example.ts",
//   "options": { "threshold": 0.8, "extraPatterns": ["custom error"] }
// }
